tests: on_target: add ppk test
Add ppk test and update badge accordingly.

Signed-off-by: Giacomo Dematteis <giacomo.dematteis@nordicsemi.no>

diff --git a/.github/workflows/on_target.yml b/.github/workflows/on_target.yml
--- a/.github/workflows/on_target.yml
+++ b/.github/workflows/on_target.yml
@@ -59,14 +59,24 @@ on:
         type: boolean
         required: true
         default: false
+      run_wifi_location_tests:
+          type: boolean
+          required: true
+          default: false
+      run_ppk_tests:
+          type: boolean
+          required: true
+          default: false
 
 jobs:
   target_test:
     name: Target Test
     runs-on: self-hosted
+    permissions:
+      contents: write
     environment: production
     container:
-      image: ghcr.io/hello-nrfcloud/firmware:docker-v1.0.0
+      image: ghcr.io/hello-nrfcloud/firmware:docker-v1.0.2
       options: --privileged
       volumes:
         - /dev:/dev:rw
@@ -183,6 +193,7 @@ jobs:
           LOG_FILENAME: oob_conn_bridge_test_log
 
       - name: Run Wi-Fi location tests
+        if: ${{ inputs.run_wifi_location_tests }}
         working-directory: thingy91x-oob/tests/on_target
         run: |
           mkdir -p results
@@ -192,20 +203,78 @@ jobs:
         env:
           SEGGER: ${{ secrets.SEGGER_DUT_1 }}
 
-      - name: Results
-        if: always()
-        uses: pmeier/pytest-results-action@v0.7.1
-        with:
-          path: thingy91x-oob/tests/on_target/results/*.xml
-          summary: true
-          fail-on-empty: true
-          title: OOB FW Test Results
+      - name: Run PPK tests
+        if: ${{ inputs.run_ppk_tests }}
+        id: ppk_test
+        working-directory: thingy91x-oob/tests/on_target
+        run: |
+          mkdir -p results
+          pytest -s -v -m dut_ppk \
+            --junit-xml=results/test-results-ppk.xml \
+            tests
+        env:
+          SEGGER: ${{ secrets.SEGGER_DUT_PPK }}
 
-      - name: Push log files to artifacts
+    #   - name: Mock Power Badge JSON Creation
+    #     working-directory: thingy91x-oob/tests/on_target
+    #     run: |
+    #       # Write the JSON content to power_badge.json in the correct location
+    #       echo '{ "label": "psm_current uA", "message": "15", "schemaVersion": 1, "color": "yellow" }' > power_badge.json
+    #     shell: bash
+
+      - name: Commit and Push Badge File to gh-pages Branch
         if: always()
-        uses: actions/upload-artifact@v4
-        id: artifact-upload-test-logs
-        with:
-          name: test-logs
-          path: |
-            thingy91x-oob/tests/on_target/outcomes/logs/*.txt
+        working-directory: thingy91x-oob/tests/on_target
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Configure Git to trust the current working directory
+          git config --global --add safe.directory /__w/firmware/firmware
+
+          # Set Git user name and email for commits in the GitHub Actions environment
+          git config --global user.email "github-actions@github.com"
+          git config --global user.name "GitHub Actions"
+
+          # Check if the badge file exists at the specified location
+          if [ -f power_badge.json ]; then
+            echo "Badge file found, proceeding to commit."
+          else
+            echo "Badge file not found. Exiting..."
+            exit 1
+          fi
+
+          # Check if the badge file exists at the specified location
+          if [ -f power_measurements_plot.html ]; then
+            echo "Html file found, proceeding to commit."
+          else
+            echo "Html file not found. Exiting..."
+            exit 1
+          fi
+
+          # Ensure the gh-pages branch exists and switch to it
+          # git fetch origin gh-pages || git checkout -b gh-pages
+          git checkout gh-pages
+
+          # Stage, commit, and push changes to the branch
+          ls
+          git add power_badge.json power_measurements_plot.html
+          git commit -m "Update power badge and html"
+          git push origin gh-pages
+
+    #   - name: Results
+    #     if: always()
+    #     uses: pmeier/pytest-results-action@v0.7.1
+    #     with:
+    #       path: thingy91x-oob/tests/on_target/results/*.xml
+    #       summary: true
+    #       fail-on-empty: true
+    #       title: OOB FW Test Results
+
+    #   - name: Push log files to artifacts
+    #     if: always()
+    #     uses: actions/upload-artifact@v4
+    #     id: artifact-upload-test-logs
+    #     with:
+    #       name: test-logs
+    #       path: |
+    #         thingy91x-oob/tests/on_target/outcomes/logs/*.txt
